### ISSUE TITLE
Conflict with with gatsby-plugin-transition-link

### ISSUE THREAD

**Issue by rodrigo-arias** [GatsbyWPGutenberg/gatsby-wordpress-gutenberg#41]
Hi Peter,

Great work with this plugin, it covers an important part of the integration between WordPress and Gatsby that was missing.

I just want to share a bug that I had a hard time finding. I started using `gatsby-theme-wordpress-gutenberg` and everything went well in develop, but when I tried to create the build I found this error

![image](https://user-images.githubusercontent.com/11416255/87839732-86b42000-c872-11ea-8308-3e8a4131e495.png)

Finally it turned out to be a conflict with `gatsby-plugin-transition-link`

By the way it would be nice to have some customization options in the plugin, like the paths for custom blocks.

Thanks

**Comment by pristas-peter** [comment]
Hi thanks for reporting this, I am planning to work on some tests which cover this in the future. 

The custom paths are intentionally not there, because of the component shadowing.
