### ISSUE TITLE
Evaluate innerBlocks

### ISSUE THREAD

**Issue by rodrigo-arias** [GatsbyWPGutenberg/gatsby-wordpress-gutenberg#42]
Hi Peter,

I am wondering if there is any way to evaluate the innerBlocks.

In this case I have an accordion and in its content it may eventually contain other blocks. Is there a way to evaluate `<Blocks/>` for those innerBlocks so that it renders the corresponding component?

```
export const query = graphql`
  fragment Accordion on WpTestAccordionBlock {
    attributes {
      ... on WpTestAccordionBlockAttributes {
        accordionTitle
      }
    }
    innerBlocks {
      originalContent
    }
  }
`

export default ({ attributes, innerBlocks }) => {
  const { accordionTitle } = attributes
  return (
    <Collapse>
      <Panel header={accordionTitle} key="1">
        {innerBlocks.map((block, key) => (
          <Fragment key={key}>{block.attributes.content}</Fragment>
        ))}
      </Panel>
    </Collapse>
  )
}
```

Thank you

**Comment by pristas-peter** [comment]
Just use the children prop. The innerBlocks are there.

**Comment by pristas-peter** [comment]
Also there is a small example of how this works here in the last section: https://gatsbywpgutenberg.netlify.app/installation/quickstart/

**Comment by rodrigo-arias** [comment]
That worked, thanks!
