### ISSUE TITLE
Issue querying CoreTableBlock

### ISSUE THREAD

**Issue by rodrigo-arias** [GatsbyWPGutenberg/gatsby-wordpress-gutenberg#44]
Hi Peter,

I am trying to query the attributes of CoreTableBlock and that works in WP but breaks in Gatsby.

![image](https://user-images.githubusercontent.com/11416255/88063291-412c7700-cb40-11ea-97d5-d598b41cad0a.png)

vs.

![image](https://user-images.githubusercontent.com/11416255/88063438-69b47100-cb40-11ea-9e33-a4b218089367.png)

Do you have any idea what might be happening?

Thanks

**Comment by TylerBarnes** [comment]
Hi @rodrigo-arias , this looks like a bug with gatsby-source-wordpress-experimental. Do you have a reproduction repo I can use to debug?

**Comment by rodrigo-arias** [comment]
Hi @TylerBarnes, yes you can use this https://github.com/rodrigo-arias/gatsby-wordpress-demo with any local installation with WPGraphQL Gutenberg. [This](https://github.com/rodrigo-arias/gatsby-wordpress-demo/blob/master/src/gatsby-theme-wordpress-gutenberg/components/blocks/core/table.js) is the block query that has a problem. Thanks!

**Comment by TylerBarnes** [comment]
This is fixed in `gatsby-source-wordpress-experimental@1.3.1`

**Comment by rodrigo-arias** [comment]
It worked perfect, thank you so much for working on this Tayler!
