### ISSUE TITLE
Blocks don't work on build time with static query

### ISSUE THREAD

**Issue by rodrigo-arias** [GatsbyWPGutenberg/gatsby-wordpress-gutenberg#47]
Hi @pristas-peter,

I am trying to do this: https://github.com/rodrigo-arias/gatsby-wordpress-demo/blob/master/src/pages/index.js

Everything works fine with develop, but breaks at build time

![image](https://user-images.githubusercontent.com/11416255/89661171-b621df80-d8a8-11ea-9910-32f1add0e39b.png)

I also found an error that maybe is related https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/105

The issue only happens using the blocks
```
"gatsby": "^2.24.31"
"gatsby-source-wordpress-experimental": "^1.2.6"
```

Do you think the static query should not affect the blocks and is there something else?

Thank you

**Comment by pristas-peter** [comment]
The were some changes in gatsby lately on how the static queries are bundled, so I guess the problem is somewhere down that road.

**Comment by rodrigo-arias** [comment]
Thanks Peter, it's good to know that you know where the issue can come from. It will be great when you get a chance to check it out
